# .goreleaser.yml
# Build customization
builds:
  - binary: jwkgen
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ldflags: '-s -w -X main.version={{.Version}} -X main.buildDate={{.Date}}'
changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

archives:
  - name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      386: x86
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

brews:
  # Reporitory to push the tap to.
  - github:
      owner: rakutentech
      name: homebrew-tap

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: boazy
      email: boazyan@gmail.com

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/rakutentech/jwkgen"

    # Your app's description.
    # Default is empty.
    description: |
      Small command-line tool that generates asymmetric JSON Web Keys for the
      following algorithms and curves

